name: sinPlayerDeath
version: '1.0.0'
main: org.sinPlayerDeath.SinPlayerDeath
api-version: '1.21'
commands:
  sinpd:
    description: Reload config plugin
    usage: /spreload
    permission: sinPlayerDeath.reload
    permission-message: You do not have permission