config_version: 1

# 0.2 = 20%
exp_lost: 0.2

money_lost:
  default: 0.1   # 10%
  vip: 0.05      # 5%
  svip: 0.02     # 2%
  mvp: 0.01      # 1%

#permission
# "sinPlayerDeath.no_drop_all"
has_permission_no_drop: true

messages:
  reload: "&aReload plugin success"
  no_permission: "&cYou not have permissions"
  money_lost: "§cTake money for you {money_take} because you die"

item_no_drop:
  - "DIAMOND"
